name: Tripster
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.6 <4.0.0"

#Enable null safety
null_safety: true

dependencies:
  flutter:
    sdk: flutter
  http:
  cupertino_icons: ^1.0.2

  flutter_localizations:
    sdk: flutter
  table_calendar: ^3.0.0
  #translation_module_start
  image_picker: ^1.0.7
  google_ml_vision: ^0.0.8
  image_cropper: 4.0.1
  permission_handler:
  #google_ml_kit: ^0.16.3
  translator:

  google_mlkit_text_recognition: ^0.11.0
  geolocator: ^11.0.0
  geocoding: ^2.2.0
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  cloud_firestore: ^4.4.3
  firebase_storage: 11.6.9
  google_sign_in: ^6.2.1
  provider: ^6.1.2
  flutter_map:
  latlong2:
  intl: ^0.18.1
  google_maps_flutter:
  search_map_place_updated:

  flutter_dotenv: ^5.1.0

  shared_preferences: ^2.2.2
  country_code_picker: ^3.0.0
  country_state_city_picker:
  tflite_flutter: ^0.10.4

  path: any
  cached_network_image: ^3.3.1
  fuzzy: ^0.5.1
  flutter_rating_bar: ^4.0.1
  drag_and_drop_lists: ^0.3.3
  share_plus: ^7.2.2
  pdf: ^3.10.8
  path_provider: ^2.1.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/ramen.png
    - assets/images/newyork.png
    - assets/images/london.png
    - assets/images/paris.png
    - assets/images/tokyo.png
    - assets/images/river.png
    - assets/images/rome.png
    - assets/images/buildings.png
    - assets/images/beach.png
    - assets/images/mountains.png
    - assets/images/dessert.png
    - assets/images/logo.png
    - assets/icons/google.png
    - assets/icons/facebook.png
    - assets/icons/apple.png
    - assets/images/profile.png
    - assets/images/france.jpg
    - assets/images/italy.jpg

  fonts:
    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico-Regular.ttf
    - family: Plus Jakarta Sans
      fonts:
        - asset: assets/fonts/PlusJakartaSans-Regular.ttf
        - asset: assets/fonts/PlusJakartaSans-Regular.ttf
        - asset: assets/fonts/PlusJakartaSans-Medium.ttf
